### PR TITLE
Add `describe` snippet to Elixir

### PR DESCRIPTION
**Pull request by ma2gedev**
There is already `test` snippet, so we also want to include `describe`.

### CODE REVIEW

**Comment by ujihisa** [comment]
`${2:TARGET}` instead of just `${2}` would be even better.

**Comment by ujihisa** [comment]
(oops, other elixir snippets aren't so, even though I think they should be)

**Comment by Shougo** [comment]
I have added TARGET.

**Comment by ma2gedev** [comment]
Sorry late response. Thank you for the advice and merging. Also thank you for the commit 2a9487bacb924d8e870612b6b0a2afb34deea0ae .

**Comment by ujihisa** [comment]
👍

**Pull request merged**
