### PR TITLE
added fortran snippet

### PR DESCRIPTION
**Pull request by robinro**
This includes a couple of basic fortran snippets. There aren't many sources of fortran snippets for vim out there. The best one I found is https://github.com/hellolife/Vim which was the basis for this file.

### CODE REVIEW

**Comment by Shougo** [comment]
Can I include it?
It is based on https://github.com/hellolife/Vim/blob/b4b84f5e0685bdccf58474d5311c094e7eab5eb4/vimfiles/autoload/neosnippet/snippets/fortran.snip.
But it is not licensed and original author is not activity in 2 years.
I think you should rewrite it.

**Comment by robinro** [comment]
I didn't do a full rewrite, but the version committed differs so much already that not much more than trivial things like basic fortran syntax and basix snippet syntax is the same. I don't believe that is enough to make it copyrightable.

What's the license of the snippets anyway?
Please consider including a `LICENSE` file to make that obvious.

**Comment by Shougo** [comment]
> What's the license of the snippets anyway?

OK.  I will include it.

**Comment by Shougo** [comment]
Added LICENSE file.

**Comment by Shougo** [comment]
This is merge-able?

**Comment by robinro** [comment]
@Shougo yes

**Comment by Shougo** [comment]
OK.

**Pull request merged**
